config/routes.rb
JxSite::Application.routes.draw do

  match '/project_euler' => 'home#p_euler', :via => :get, :as => :p_euler_home
  resources :blogs

  root :to => 'home#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :content, :title, :email
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :access_granted
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ChefHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(params[:blog])
    if @blog.save
      redirect_to @blog
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update_attributes(params[:blog])
      redirect_to @blog
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    if @blog.destroy
      redirect_to blogs_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def p_euler
    PEuler.methods(false).each do |problem|
      @problem_sources ||= [] << [
        cook(PEuler.method(problem)),
        PEuler.send(problem)]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:error, :info, :success, :warning]

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
      
      type = :success if type == :notice
      type = :error   if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if message
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/chef_helper.rb
module ChefHelper
  def cook(food)
    CodeChef::RubyChef.new.cook(food)
  end
end

app/views/blogs/_blog.html.erb
<p>
  <%= link_to 'Edit', edit_blog_path(blog) %>
  <%= link_to 'Remove', blog, :method => :delete %>
</p>
<p>
  <%= blog.email %>
</p>
<p>
  <%= blog.title %>
</p>
<p>
  <%= blog.content %>
</p>

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
  email: <%= f.text_field :email %>
  title: <%= f.text_field :title %>
  content: <%= f.text_area :content %>
  <%= f.submit 'Post' %>
<% end %>

app/views/blogs/edit.html.erb
Edit blog
<%= render 'form' %>

app/views/blogs/index.html.erb
<%= link_to t('.new'), new_blog_path %>

<h1><%= t('.title') %></h1>
<% @blogs.each do |blog| %>
  <p>
    <%= link_to blog.title, blog_path(blog) %>
    by <%= blog.email %>
  </p>
<% end %>

app/views/blogs/new.html.erb
New blog
<%= render 'form' %>

app/views/blogs/show.html.erb
<%= render @blog %>

app/views/home/index.html.erb
<%= "Hello World" %>

app/views/home/p_euler.html.erb
<h1>Project Euler</h1>
<h2>problems</h2>

<% @problem_sources.each do |source_and_answer| %>
  <%= raw CodeRay.scan(source_and_answer[0], :ruby).div(:css => :class) %>
  <%= t '.my_answer', answer: source_and_answer[1] %>
<% end %>

app/views/layouts/_footer.html.erb
<p>&copy; <%= t('.signiture') %> 2013</p>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#"><%= t('.title') %></a>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to t('.nav.home'), root_path %></li>
          <li><%= link_to t('.nav.blogs'), blogs_path %></li>
          <li><%= link_to t('.nav.p_euler'), p_euler_home_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <h3><%= t('.title') %></h3>
    <ul class="nav nav-list">
      <li class="nav-header"><%= t('.title') %></li>
      <li><%= link_to "Link1", "/path1"  %></li>
      <li><%= link_to "Link2", "/path2"  %></li>
      <li><%= link_to "Link3", "/path3"  %></li>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t('.title') %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%# <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%# <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%# <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%# <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%# <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <%= render 'layouts/sidebar' %>
        </div><!--/row-->

      <footer>
        <%= render 'layouts/footer' %>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>